version: '3.9'
services: 
  mongodb:
    image: mongo
    ports: 
      - 27017:27017                           # HOST-IP: Container-IP            
    volumes: 
      - mongodb-data:/data/db                 # Data location in the mongo image. Check the documentation for mongodb
    environment:                            
      - MONGO_INITDB_ROOT_USERNAME=root       
      - MONGO_INITDB_ROOT_PASSWORD=toor
  mongo-express:
    image: mongo-express
    ports: 
      - 8081:8081
    environment: 
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=toor
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mongodb-data:
    driver: local                           # Named volume. Data is not lost during local development